"""
This type stub file was generated by pyright.
"""

import logging
import importlib
import pkgutil

logger = ...
__version__ = ...
__author__ = ...
__email__ = ...
__license__ = ...

class Shortener:
    """Base Factory class to create shoreteners instances

    >>> s = Shortener(**kwargs)
    >>> instance = s.shortener_name
    >>> instance.short('http://www.google.com')
    'http://short.url/'

    Available Shorteners can be seen with:

    >>> s = Shortener()
    >>> print(s.available_shorteners)
    """

    def __init__(self, **kwargs) -> None: ...
    def __getattr__(self, attr) -> Any: ...
