"""
This type stub file was generated by pyright.
"""

class ShorteningErrorException(Exception):
    def __init__(self, message=...) -> None:
        ...
    


class ExpandingErrorException(Exception):
    def __init__(self, message=...) -> None:
        ...
    


class BadAPIResponseException(Exception):
    def __init__(self, message) -> None:
        ...
    


class BadURLException(Exception):
    def __init__(self, message) -> None:
        ...
    


