"""
This type stub file was generated by pyright.
"""

class _Comparable:
    """Implements rich comparison if __lt__ and __eq__ are provided."""
    def __gt__(self, other: _Comparable: _Comparable) -> bool:
        ...

    def __le__(self, other: _Comparable) -> bool:
        ...

    def __ne__(self, other: _Comparable) -> bool:
        ...

    def __ge__(self, other: _Comparable) -> bool:
        ...


class Version(_Comparable):
    def __init__(self, version: str) -> None:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self): # -> str:
        ...

    def __lt__(self, other: Version) -> bool:
        ...

    def __eq__(self, other: Version) -> bool:
        ...

